### ISSUE TITLE
Confusing versioning

### ISSUE THREAD

**Issue by gongdo** [NexClipper/NexClipper#18]
https://github.com/NexClipper/NexClipper/releases/tag/v0.9.1
It is tagged as `v0.9.1` but the title is `v0.1`, even more confusing `#v0.10(2018-0322)` in description.
Not a big deal to use, but it's... little bit annoying.

**Comment by nexclouding** [comment]
Sorry for that. It was depreciated release which was tagged as v0.9.1
It'll be fixed soon.
Thanks for your comment.
