### ISSUE TITLE
collector and dashboard service port needs added

### ISSUE THREAD

**Issue by coolpalani** [NexClipper/NexClipper#22]
Hello,

I tried to setup NexClipper in Kubernetes cluster and able to setup but UI isn't working.
it seems collector and service ports are creating from random Nodeport.
I was locally able to fix this and dashboard working. I tried to contribute the fix code through pull request, but not able to push due to permission issue.

**Comment by nexclouding** [comment]
Thank a lot.
Do you mean you can't request PR? Could you give some more detail about issue of permission? We don't set particular permission for some users.,
