### ISSUE TITLE
Misspelled words

### ISSUE THREAD

**Issue by achilleslinux** [NexClipper/NexClipper#27]
I have found a misspelled word on the nexclipper website. Please look at the word FULL STACK DASHBOARD

![Screenshot from 2019-04-24 12-30-26](https://user-images.githubusercontent.com/12483219/56638970-1f1e1d80-668d-11e9-9e1b-6499de81e0b3.png)

**Comment by nexclouding** [comment]
Thanks for your comments. We'll fix it.

**Comment by junesvon** [comment]
Thank you for Ur hawkeye.
