### ISSUE TITLE
deployment of nexclipper-collector is wrong

### ISSUE THREAD

**Issue by Jooho** [NexClipper/NexClipper#35]
The image tag "k8s-test" does not exist.

need to change it to k8s.

Moreover, the way to distribute helm chart with tgz(nexclipper-0.1.0.tgz) style is not a good idea because I can not contribute this kind simple issue. Why don't you separate it from the main project?

**Comment by devleeskNex** [comment]
Hello,
We used "k8s-test" in the testing process. I changed it to "k8s" and uploaded it. Could you tell me where I saw "k8s-test"? I need to fix it.
I will remove tgz (nexclipper-0.1.0.tgz) and separate the project.
Thanks for your comments.
