### ISSUE TITLE
java.io.FileNotFoundException: mylog-2019-05-30.0.txt (Permission denied)

### ISSUE THREAD

**Issue by Jooho** [NexClipper/NexClipper#38]
Normally, container should not store logs inside container and Kuberentes is as well. If you want to store data like log from container, you should use PV and specify absolute path. 
However,  the NexCollector application try to use rolling log so it failed because of permission issue.
```
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[ROLLING] - openFile(null,true) call failed. java.io.FileNotFoundException: mylog-2019-05-30.0.txt (Permission denied)
```
I tried to fix it but there are a lot dependencies of the application like Kafka. Even though, I just try to fix this simple log issue, should I setup all eco system?

**Comment by prasenforu** [comment]
@jooho can you please help me how you tried to fix log permission issue.

Also can you tell me location of that log file.

**Comment by devleeskNex** [comment]
Hi.
We tested several times. However, we did not find a corresponding phenomenon.
Can you tell me what cloud you're working on?
We want to solve this problem.
Thank you.

**Comment by prasenforu** [comment]
Looks like its a container permission issue.

Need to run with root privileges.
